# BÀI TẬP: TITANIC
**Nguồn:** kaggle.com/c/titanic (891 dòng)

In [1]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
from pathlib import Path
from scipy import stats

sns.set_style('whitegrid')

csv_path = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv'

df = pd.read_csv(csv_path)
print('Loaded from:', csv_path)
df.head()

Loaded from: https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [2]:
#
import pandas as pd
#đọc 
df = pd.read_csv(csv_path)

In [3]:
#hiển thị 5 dòng đầu tiên
df.head(5)
df.tail()
df.head()
#hoặc
#
display(df.head())
#hiển thị 5 dòng cuối
display(df.tail())

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

---
# PHẦN A — DATA PROFILING
## A.1. Data size, column names, data types

In [4]:
# TODO
#data size(xem dòng và cột)
print("data size: ", df.shape)

data size:  (891, 15)

In [5]:
#xem thông tin tổng quan(xem dòng và cột)
df.info

<bound method DataFrame.info of      survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False  NaN  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]>

In [6]:
#column names(xem tên các cột)
print("columns: ",df.columns)

columns:  Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [7]:
#data types(xem kiểu data)
df.dtypes

survived         int64
pclass           int64
sex             object
age            float64
sibsp            int64
parch            int64
fare           float64
embarked        object
class           object
who             object
adult_male        bool
deck            object
embark_town     object
alive           object
alone             bool
dtype: object

## A.2. Missing values & Duplicate data

In [8]:
# TODO
#Missing values (giá trị bị thiếu)
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [9]:
#duplicate data(data trùng)
print("duplicate data:", df.duplicated().sum())

#điếm trùng
print("duplicate data: ",df.duplicated().count())

duplicate data: 107
duplicate data:  891

## A.3. Invalid values

In [ ]:
# Invalid values(các giá trị hợp lệ không)unique
print(df['sibsp'].unique())

[1 0 3 4 2 5 8]

In [12]:
df.loc[df['sibsp'] < 0, 'sibsp'] = np.nan

## A.4. Create a new column
Tạo cột `family_size` = sibsp + parch + 1.

In [14]:
# TODO
df['family_size'] = df['sibsp'] + df['parch'] + 1
print(df)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0    1.0      0   7.2500        S   Third
1           1       1  female  38.0    1.0      0  71.2833        C   First
2           1       3  female  26.0    0.0      0   7.9250        S   Third
3           1       1  female  35.0    1.0      0  53.1000        S   First
4           0       3    male  35.0    0.0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0    0.0      0  13.0000        S  Second
887         1       1  female  19.0    0.0      0  30.0000        S   First
888         0       3  female   NaN    1.0      2  23.4500        S   Third
889         1       1    male  26.0    0.0      0  30.0000        C   First
890         0       3    male  32.0    0.0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone  family_size
0      man        True  NaN  Southampton    no  False          2.0
1    woman       False    C    Cherbourg   yes  False          2.0
2    woman       False  NaN  Southampton   yes   True          1.0
3    woman       False    C  Southampton   yes  False          2.0
4      man        True  NaN  Southampton    no   True          1.0
..     ...         ...  ...          ...   ...    ...          ...
886    man        True  NaN  Southampton    no   True          1.0
887  woman       False    B  Southampton   yes   True          1.0
888  woman       False  NaN  Southampton    no  False          4.0
889    man        True    C    Cherbourg   yes   True          1.0
890    man        True  NaN   Queenstown    no   True          1.0

[891 rows x 16 columns]

---
# PHẦN B — DESCRIPTIVE STATISTICS
## Group 1 — Central Tendency

In [16]:
# TODO
print("mean: ",df['age'].mean())

mean:  29.69911764705882

In [ ]:
print("median: ", df['age'].median())

median:  28.0

In [19]:
print("mode: ", df['age'].mode())

mode:  0    24.0
Name: age, dtype: float64

## Group 2 — Dispersion

In [ ]:
#độ phân tán

In [21]:
# TODO
#khoản cách giá lớn nhất và nhỏ nhất
print(df['age'].max() - df['age'].min())

79.58

In [24]:
#phương sai(var)
print(df['age'].var())

211.01912474630802

In [26]:
#độ lệch chuẩn(std)
print(df['age'].std())

14.526497332334042

## Group 3 — Location and Shape

In [ ]:
# TODO
#vị trí(location) skew() chọn độ lệch
print("skew: ", df['age'].skew())

skew:  0.38910778230082704

In [29]:
#độ chọn, kurt()
print("kurt: ", df['age'].kurt())

kurt:  0.17827415364210353

---
# PHẦN C — DEFINE THE QUESTION

## Câu hỏi 1: Hạng vé nào có tỷ lệ sống sót cao nhất, chênh lệch bao nhiêu so với hạng thấp nhất?

In [30]:
# TODO
        # Tỷ lệ sống sót theo hạng vé
survival_rate = df.groupby('class')['survived'].mean() * 100


        # Chênh lệch cao nhất và thấp nhất
difference = survival_rate.max() - survival_rate.min()



print("Hạng vé sống sót cao nhất:", survival_rate.idxmax())
print("Tỷ lệ sống sót:", round(survival_rate.max(), 2), "%")
print("Chênh lệch:", round(difference, 2), "%")

Hạng vé sống sót cao nhất: First
Tỷ lệ sống sót: 62.96 %
Chênh lệch: 38.73 %

## Câu hỏi 2: Giới tính hay hạng vé ảnh hưởng đến sống sót mạnh hơn?

In [31]:
# TODO
# Tỷ lệ sống sót theo giới tính
gender_survival = df.groupby('sex')['survived'].mean() * 100
print("Tỷ lệ sống sót theo giới tính:")
print(gender_survival)


# Tỷ lệ sống sót theo hạng vé
class_survival = df.groupby('class')['survived'].mean() * 100
print("\nTỷ lệ sống sót theo hạng vé:")
print(class_survival)

Tỷ lệ sống sót theo giới tính:
sex
female    74.203822
male      18.890815
Name: survived, dtype: float64

Tỷ lệ sống sót theo hạng vé:
class
First     62.962963
Second    47.282609
Third     24.236253
Name: survived, dtype: float64

## Câu hỏi 3: Vé đắt hơn có thực sự sống sót cao hơn không?

In [32]:
# TODO
# Chia giá vé thành 3 nhóm
df['fare_group'] = pd.qcut(df['fare'], 3)

# Tính tỷ lệ sống sót theo giá vé
fare_survival = df.groupby('fare_group', observed=True)['survived'].mean() * 100

print(fare_survival)

fare_group
(-0.001, 8.662]    19.805195
(8.662, 26.0]      40.277778
(26.0, 512.329]    55.932203
Name: survived, dtype: float64

## Câu hỏi 4: Gia đình đông người có ảnh hưởng đến khả năng sống sót không?

In [33]:
# TODO
# Tính số người trong gia đình
df['family_size'] = df['sibsp'] + df['parch'] + 1

# Tính tỷ lệ sống sót theo quy mô gia đình
family_survival = df.groupby('family_size')['survived'].mean() * 100

print(family_survival)

family_size
1.0     30.353818
2.0     55.279503
3.0     57.843137
4.0     72.413793
5.0     20.000000
6.0     13.636364
7.0     33.333333
8.0      0.000000
11.0     0.000000
Name: survived, dtype: float64

## Câu hỏi 5: Cảng lên tàu (embark_town) nào có tỷ lệ sống sót cao nhất?

In [ ]:
# TODO***********************************
# Tỷ lệ sống sót theo cảng lên tàu
embark_survival = df.groupby('embark_town')['survived'].mean() * 100

print(embark_survival)

# Cảng có tỷ lệ sống sót cao nhất
print("Cảng có tỷ lệ sống sót cao nhất:", embark_survival.idxmax())
print("Tỷ lệ:", round(embark_survival.max(), 2), "%")

embark_town
Cherbourg      55.357143
Queenstown     38.961039
Southampton    33.695652
Name: survived, dtype: float64
Cảng có tỷ lệ sống sót cao nhất: Cherbourg
Tỷ lệ: 55.36 %

## Câu hỏi 6 (Tổng hợp) — Viết insight tổng hợp
Dựa trên Phần A, B, C, viết 4-5 câu insight tổng thể về dữ liệu Titanic.

*(Viết insight của bạn vào đây...)*